#!/bin/bash
#SBATCH --mem=20G
#SBATCH --cpus-per-task=8
#SBATCH --nodelist=ml-512-node-057,ml-512-node-058,,ml-512-node-059,,ml-512-node-060

source $(pwd)/../venv/bin/activate

# Get the name of the agent
current_path=$(pwd)
agent=$(echo "$current_path" | awk -F'ml-1cc/' '{print $2}' | awk -F'/' '{print $1}')

python $(pwd)/train_llm.py \
    --experiment-name ${agent}-gpt2-youtube-comments-v2-single-gpu-$(date +%y%m%d%H%M%S) \
    --dataset-name breadlicker45/youtube-comments-v2 \
    --model-name openai-community/gpt2 \
    --batch-size 64 \
    --num-epochs 2 \
    --ckpt-freq 100 \
    --log-freq 10